CREATE TABLE `processmap` (
	`defId` VARCHAR(50) NOT NULL DEFAULT '',
	`name` VARCHAR(50) NULL DEFAULT NULL,
	`iconPath` VARCHAR(255) NULL DEFAULT NULL,
	`color` VARCHAR(10) NULL DEFAULT NULL,
	`no` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`defId`)
)