DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS marketItem;

CREATE TABLE category(
categoryId INTEGER NOT NULL,
categoryName  VARCHAR(255) NOT NULL,
parentCategoryId INTEGER DEFAULT -1,
modDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
deleted INTEGER DEFAULT 0,
  CONSTRAINT category
  PRIMARY KEY ( categoryId )
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE marketItem(
itemId INTEGER NOT NULL,
categoryId INTEGER NOT NULL,
itemName VARCHAR(255) NOT NULL,
description VARCHAR(1000) NOT NULL,
version INTEGER NOT NULL,
comCode  VARCHAR(30) NOT NULL,
price INTEGER NOT NULL,
filePath VARCHAR(255) NOT NULL,
logoImageFilePath VARCHAR(255),
imageFile1Path VARCHAR(255),
imageFile2Path VARCHAR(255),
imageFile3Path VARCHAR(255),
imageFile4Path VARCHAR(255),
imageFile5Path VARCHAR(255),
regDate DATETIME DEFAULT NULL,
starPoint INTEGER,
deleted INTEGER DEFAULT 0,
modDate TIMESTAMP DEFAULT NOW(),
  CONSTRAINT marketItem
  PRIMARY KEY ( itemId )
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
